INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (1, 'Afghanistan', 'AFG', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (2, 'Albania', 'ALB', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (3, 'Algeria', 'DZA', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (4, 'American Samoa', 'ASM', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (5, 'Andorra', 'AND', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (6, 'Angola', 'AGO', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (7, 'Anguilla', 'AIA', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (8, 'Antarctica', 'ATA', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (9, 'Antigua and Barbuda', 'ATG', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (10, 'Argentina', 'ARG', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (11, 'Armenia', 'ARM', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (12, 'Aruba', 'ABW', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (13, 'Australia', 'AUS', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (14, 'Austria', 'AUT', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (15, 'Azerbaijan', 'AZE', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (16, 'Bahamas', 'BHS', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (17, 'Bahrain', 'BHR', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (18, 'Bangladesh', 'BGD', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (19, 'Barbados', 'BRB', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (20, 'Belarus', 'BLR', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (21, 'Belgium', 'BEL', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (22, 'Belize', 'BLZ', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (23, 'Benin', 'BEN', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (24, 'Bermuda', 'BMU', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (25, 'Bhutan', 'BTN', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (26, 'Bolivia', 'BOL', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (27, 'Bosnia and Herzegowina', 'BIH', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (28, 'Botswana', 'BWA', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (29, 'Bouvet Island', 'BVT', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (30, 'Brazil', 'BRA', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (31, 'British Indian Ocean Territory', 'IOT', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (32, 'Brunei Darussalam', 'BRN', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (33, 'Bulgaria', 'BGR', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (34, 'Burkina Faso', 'BFA', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (35, 'Burundi', 'BDI', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (36, 'Cambodia', 'KHM', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (37, 'Cameroon', 'CMR', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (38, 'Canada', 'CAN', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (39, 'Cape Verde', 'CPV', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (40, 'Cayman Islands', 'CYM', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (41, 'Central African Republic', 'CAF', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (42, 'Chad', 'TCD', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (43, 'Chile', 'CHL', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (44, 'China', 'CHN', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (45, 'Christmas Island', 'CXR', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (46, 'Cocos (Keeling) Islands', 'CCK', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (47, 'Colombia', 'COL', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (48, 'Comoros', 'COM', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (49, 'Congo', 'COG', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (50, 'Cook Islands', 'COK', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (51, 'Costa Rica', 'CRI', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (52, 'Cote D\'Ivoire', 'CIV', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (53, 'Croatia', 'HRV', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (54, 'Cuba', 'CUB', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (55, 'Cyprus', 'CYP', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (56, 'Czech Republic', 'CZE', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (57, 'Denmark', 'DNK', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (58, 'Djibouti', 'DJI', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (59, 'Dominica', 'DMA', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (60, 'Dominican Republic', 'DOM', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (61, 'East Timor', 'TMP', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (62, 'Ecuador', 'ECU', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (63, 'Egypt', 'EGY', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (64, 'El Salvador', 'SLV', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (65, 'Equatorial Guinea', 'GNQ', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (66, 'Eritrea', 'ERI', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (67, 'Estonia', 'EST', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (68, 'Ethiopia', 'ETH', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (69, 'Falkland Islands (Malvinas)', 'FLK', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (70, 'Faroe Islands', 'FRO', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (71, 'Fiji', 'FJI', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (72, 'Finland', 'FIN', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (73, 'France', 'FRA', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (74, 'France, Metropolitan', 'FXX', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (75, 'French Guiana', 'GUF', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (76, 'French Polynesia', 'PYF', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (77, 'French Southern Territories', 'ATF', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (78, 'Gabon', 'GAB', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (79, 'Gambia', 'GMB', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (80, 'Georgia', 'GEO', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (81, 'Germany', 'DEU', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (82, 'Ghana', 'GHA', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (83, 'Gibraltar', 'GIB', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (84, 'Greece', 'GRC', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (85, 'Greenland', 'GRL', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (86, 'Grenada', 'GRD', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (87, 'Guadeloupe', 'GLP', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (88, 'Guam', 'GUM', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (89, 'Guatemala', 'GTM', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (90, 'Guinea', 'GIN', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (91, 'Guinea-bissau', 'GNB', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (92, 'Guyana', 'GUY', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (93, 'Haiti', 'HTI', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (94, 'Heard and Mc Donald Islands', 'HMD', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (95, 'Honduras', 'HND', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (96, 'Hong Kong', 'HKG', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (97, 'Hungary', 'HUN', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (98, 'Iceland', 'ISL', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (99, 'India', 'IND', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (100, 'Indonesia', 'IDN', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (101, 'Iran (Islamic Republic of)', 'IRN', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (102, 'Iraq', 'IRQ', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (103, 'Ireland', 'IRL', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (104, 'Israel', 'ISR', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (105, 'Italy', 'ITA', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (106, 'Jamaica', 'JAM', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (107, 'Japan', 'JPN', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (108, 'Jordan', 'JOR', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (109, 'Kazakhstan', 'KAZ', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (110, 'Kenya', 'KEN', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (111, 'Kiribati', 'KIR', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (112, 'Korea, Democratic People\'s Republic of', 'PRK', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (113, 'Korea, Republic of', 'KOR', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (114, 'Kuwait', 'KWT', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (115, 'Kyrgyzstan', 'KGZ', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (116, 'Lao People\'s Democratic Republic', 'LAO', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (117, 'Latvia', 'LVA', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (118, 'Lebanon', 'LBN', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (119, 'Lesotho', 'LSO', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (120, 'Liberia', 'LBR', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (121, 'Libyan Arab Jamahiriya', 'LBY', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (122, 'Liechtenstein', 'LIE', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (123, 'Lithuania', 'LTU', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (124, 'Luxembourg', 'LUX', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (125, 'Macau', 'MAC', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (126, 'Macedonia, The Former Yugoslav Republic of', 'MKD', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (127, 'Madagascar', 'MDG', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (128, 'Malawi', 'MWI', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (129, 'Malaysia', 'MYS', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (130, 'Maldives', 'MDV', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (131, 'Mali', 'MLI', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (132, 'Malta', 'MLT', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (133, 'Marshall Islands', 'MHL', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (134, 'Martinique', 'MTQ', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (135, 'Mauritania', 'MRT', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (136, 'Mauritius', 'MUS', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (137, 'Mayotte', 'MYT', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (138, 'Mexico', 'MEX', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (139, 'Micronesia, Federated States of', 'FSM', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (140, 'Moldova, Republic of', 'MDA', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (141, 'Monaco', 'MCO', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (142, 'Mongolia', 'MNG', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (143, 'Montserrat', 'MSR', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (144, 'Morocco', 'MAR', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (145, 'Mozambique', 'MOZ', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (146, 'Myanmar', 'MMR', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (147, 'Namibia', 'NAM', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (148, 'Nauru', 'NRU', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (149, 'Nepal', 'NPL', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (150, 'Netherlands', 'NLD', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (151, 'Netherlands Antilles', 'ANT', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (152, 'New Caledonia', 'NCL', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (153, 'New Zealand', 'NZL', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (154, 'Nicaragua', 'NIC', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (155, 'Niger', 'NER', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (156, 'Nigeria', 'NGA', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (157, 'Niue', 'NIU', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (158, 'Norfolk Island', 'NFK', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (159, 'Northern Mariana Islands', 'MNP', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (160, 'Norway', 'NOR', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (161, 'Oman', 'OMN', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (162, 'Pakistan', 'PAK', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (163, 'Palau', 'PLW', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (164, 'Panama', 'PAN', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (165, 'Papua New Guinea', 'PNG', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (166, 'Paraguay', 'PRY', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (167, 'Peru', 'PER', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (168, 'Philippines', 'PHL', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (169, 'Pitcairn', 'PCN', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (170, 'Poland', 'POL', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (171, 'Portugal', 'PRT', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (172, 'Puerto Rico', 'PRI', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (173, 'Qatar', 'QAT', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (174, 'Reunion', 'REU', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (175, 'Romania', 'ROM', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (176, 'Russian Federation', 'RUS', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (177, 'Rwanda', 'RWA', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (178, 'Saint Kitts and Nevis', 'KNA', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (179, 'Saint Lucia', 'LCA', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (180, 'Saint Vincent and the Grenadines', 'VCT', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (181, 'Samoa', 'WSM', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (182, 'San Marino', 'SMR', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (183, 'Sao Tome and Principe', 'STP', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (184, 'Saudi Arabia', 'SAU', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (185, 'Senegal', 'SEN', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (186, 'Seychelles', 'SYC', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (187, 'Sierra Leone', 'SLE', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (188, 'Singapore', 'SGP', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (189, 'Slovakia (Slovak Republic)', 'SVK', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (190, 'Slovenia', 'SVN', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (191, 'Solomon Islands', 'SLB', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (192, 'Somalia', 'SOM', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (193, 'South Africa', 'ZAF', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (194, 'South Georgia and the South Sandwich Islands', 'SGS', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (195, 'Spain', 'ESP', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (196, 'Sri Lanka', 'LKA', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (197, 'St. Helena', 'SHN', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (198, 'St. Pierre and Miquelon', 'SPM', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (199, 'Sudan', 'SDN', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (200, 'Suriname', 'SUR', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (201, 'Svalbard and Jan Mayen Islands', 'SJM', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (202, 'Swaziland', 'SWZ', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (203, 'Sweden', 'SWE', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (204, 'Switzerland', 'CHE', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (205, 'Syrian Arab Republic', 'SYR', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (206, 'Taiwan', 'TWN', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (207, 'Tajikistan', 'TJK', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (208, 'Tanzania, United Republic of', 'TZA', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (209, 'Thailand', 'THA', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (210, 'Togo', 'TGO', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (211, 'Tokelau', 'TKL', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (212, 'Tonga', 'TON', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (213, 'Trinidad and Tobago', 'TTO', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (214, 'Tunisia', 'TUN', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (215, 'Turkey', 'TUR', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (216, 'Turkmenistan', 'TKM', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (217, 'Turks and Caicos Islands', 'TCA', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (218, 'Tuvalu', 'TUV', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (219, 'Uganda', 'UGA', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (220, 'Ukraine', 'UKR', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (221, 'United Arab Emirates', 'ARE', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (222, 'United Kingdom', 'GBR', 'Y');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (223, 'United States', 'USA', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (224, 'United States Minor Outlying Islands', 'UMI', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (225, 'Uruguay', 'URY', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (226, 'Uzbekistan', 'UZB', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (227, 'Vanuatu', 'VUT', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (228, 'Vatican City State', 'VAT', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (229, 'Venezuela', 'VEN', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (230, 'Viet Nam', 'VNM', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (231, 'Virgin Islands (British)', 'VGB', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (232, 'Virgin Islands (U.S.)', 'VIR', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (233, 'Wallis and Futuna Islands', 'WLF', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (234, 'Western Sahara', 'ESH', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (235, 'Yemen', 'YEM', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (236, 'Yugoslavia', 'YUG', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (237, 'Zaire', 'ZAR', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (238, 'Zambia', 'ZMB', 'N');
INSERT INTO `countries` (`Country_ID`, `Country`, `ISO_Code`, `Allow_Sales`) VALUES (239, 'Zimbabwe', 'ZWE', 'N');
