CREATE TABLE `users` (
	`ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`Name_Title` VARCHAR(5) NULL DEFAULT '',
	`Name_First` VARCHAR(60) NOT NULL DEFAULT '',
	`Name_Initial` CHAR(1) NULL DEFAULT '',
	`Name_Last` VARCHAR(60) NOT NULL DEFAULT '',
	`Address_ID` INT(11) UNSIGNED NULL DEFAULT '0',
	`User_phone` VARCHAR(40) NULL DEFAULT '',
	`User_email` VARCHAR(100) NOT NULL DEFAULT '',
	`User_password` VARCHAR(64) NOT NULL DEFAULT '',
	`User_url` VARCHAR(100) NOT NULL DEFAULT '',
	`User_registered` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`User_status` INT(11) NOT NULL DEFAULT '0',
	`User_level`  INT(2) NOT NULL DEFAULT '0',
	`display_name` VARCHAR(250) NOT NULL DEFAULT '',
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1;
